In [1]:
import numpy as np

In [2]:
bus_coors = np.array([
    [121, 30],
    [120, 31],
    [123, 29],
    [121.5, 30]
])

In [3]:
bus_coors.shape

(4, 2)

In [37]:

np.stack([1,2], axis=-1)[:, None]

array([[1],
       [2]])

In [20]:
# float, float -> (1,1,2)
# array, array -> (N,1,2)

np.stack([np.array([1,2,3]),np.array([4,5,6])], axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
yb_coors = np.array([
    [110, 20],
    [110, 21],
    [113, 19]
    ])

In [6]:
yb_coors.shape

(3, 2)

In [33]:
yb_coors = np.stack([100, 30], axis= -1)

In [34]:
yb_coors[:,np.newaxis].shape

(2, 1)

In [54]:
ab = (bus_coors[:,np.newaxis,:] - np.array([100,20]))
ab

# (1,4,2) -
# (3,1,2)

## if scalar
# (1,4,2) -
# (, , 2)
# 1,4,2

array([[[21. , 10. ]],

       [[20. , 11. ]],

       [[23. ,  9. ]],

       [[21.5, 10. ]]])

In [39]:
ab.shape

(1, 4, 2)

In [42]:
np.linalg.norm(ab, axis=2)

array([[23.2594067 , 22.82542442, 24.69817807, 23.7118114 ]])

In [43]:
def some_fn(x, y):
    a = np.stack([x, y], axis=-1)
    a_shape = (1, 1, 2) if np.isscalar(x) and np.isscalar(y) else (-1, 1, 2)
    a = a.reshape(a_shape)
    return a

In [47]:
some_fn(np.array([1,2,3,4]), np.array([100,200,300,400])).shape

(4, 1, 2)

In [48]:
np.stack([1,100], axis=-1)

array([  1, 100])

In [52]:
np.stack([1,100], axis=-1).shape

(2,)

In [51]:
np.stack([np.array([1,2,3,4]), np.array([100,200,300,400])], axis=-1)

array([[  1, 100],
       [  2, 200],
       [  3, 300],
       [  4, 400]])

In [53]:
np.stack([np.array([1,2,3,4]), np.array([100,200,300,400])], axis=-1).shape

(4, 2)

In [55]:
(bus_coors[:,np.newaxis,:] - np.array([100,20]))

array([[[21. , 10. ]],

       [[20. , 11. ]],

       [[23. ,  9. ]],

       [[21.5, 10. ]]])

In [56]:
(bus_coors[:,np.newaxis,:] - np.stack([np.array([1,2,3,4]), np.array([100,200,300,400])], axis=-1))

array([[[ 120. ,  -70. ],
        [ 119. , -170. ],
        [ 118. , -270. ],
        [ 117. , -370. ]],

       [[ 119. ,  -69. ],
        [ 118. , -169. ],
        [ 117. , -269. ],
        [ 116. , -369. ]],

       [[ 122. ,  -71. ],
        [ 121. , -171. ],
        [ 120. , -271. ],
        [ 119. , -371. ]],

       [[ 120.5,  -70. ],
        [ 119.5, -170. ],
        [ 118.5, -270. ],
        [ 117.5, -370. ]]])

In [57]:
def bcast(x,y):
    """ Shape: (Bus coors, YB coords, coord)"""
    return bus_coors[:,None,:] - np.stack([x,y], axis=-1)

In [58]:
bus_coors

array([[121. ,  30. ],
       [120. ,  31. ],
       [123. ,  29. ],
       [121.5,  30. ]])

In [85]:
complex_4_3 = np.linalg.norm(
    bcast([120,120,120], [30,30,30])
    ,axis=-1
) > 1.5
complex_4_3

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [83]:
np.linalg.norm(
    bcast(100,30),
    axis=-1
) >1.5

array([[ True],
       [ True],
       [ True],
       [ True]])

In [84]:
quant = np.array([1,2,3,4])

In [90]:
np.sum(quant * complex_4_3.T, axis=-1)

array([3, 3, 3])

In [8]:
import numpy as np
T=10
N=5

fake_outcome = np.random.randint(0,10,(N,T,2))
connection = np.array([
    [0,1,1,0,0],
    [1,0,0,1,1],
    [1,0,0,0,0],
    [0,1,0,0,1],
    [0,1,0,1,0]
])

In [12]:
fake_outcome[2,1,:]

array([8, 9])

In [21]:
es = np.einsum("ij, jtl -> itl", connection, fake_outcome)

In [16]:
fake_outcome[:,0,:]

array([[1, 8],
       [5, 0],
       [8, 1],
       [0, 4],
       [7, 5]])

In [22]:
es[:,0,:]

array([[13,  1],
       [ 8, 17],
       [ 1,  8],
       [12,  5],
       [ 5,  4]])

In [24]:
fake_outcome.reshape((-1,2)).reshape(N,T,2)

array([[[1, 8],
        [7, 7],
        [9, 8],
        [1, 9],
        [8, 9],
        [5, 0],
        [0, 7],
        [7, 9],
        [8, 3],
        [5, 1]],

       [[5, 0],
        [4, 9],
        [4, 0],
        [9, 8],
        [0, 6],
        [8, 4],
        [9, 9],
        [6, 0],
        [9, 7],
        [6, 3]],

       [[8, 1],
        [8, 9],
        [1, 7],
        [2, 7],
        [9, 6],
        [5, 8],
        [0, 0],
        [4, 2],
        [1, 0],
        [2, 6]],

       [[0, 4],
        [9, 0],
        [3, 0],
        [9, 3],
        [4, 4],
        [7, 7],
        [8, 5],
        [1, 6],
        [7, 5],
        [4, 4]],

       [[7, 5],
        [8, 3],
        [5, 3],
        [4, 2],
        [1, 6],
        [2, 0],
        [7, 7],
        [4, 9],
        [2, 5],
        [6, 3]]])